// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ChooseInterventionReducer from "../choose_intervention_reducer";
import EnsureSessionReducer from "../ensure_session_reducer";
import ResetMissionReducer from "../reset_mission_reducer";
import RunSimulationReducer from "../run_simulation_reducer";
import SeedCityMemoryReducer from "../seed_city_memory_reducer";
import SeedDataSourceReducer from "../seed_data_source_reducer";
import SeedInterventionReducer from "../seed_intervention_reducer";
import SeedMissionReducer from "../seed_mission_reducer";
import SetModeReducer from "../set_mode_reducer";

export type ChooseInterventionParams = __Infer<typeof ChooseInterventionReducer>;
export type EnsureSessionParams = __Infer<typeof EnsureSessionReducer>;
export type ResetMissionParams = __Infer<typeof ResetMissionReducer>;
export type RunSimulationParams = __Infer<typeof RunSimulationReducer>;
export type SeedCityMemoryParams = __Infer<typeof SeedCityMemoryReducer>;
export type SeedDataSourceParams = __Infer<typeof SeedDataSourceReducer>;
export type SeedInterventionParams = __Infer<typeof SeedInterventionReducer>;
export type SeedMissionParams = __Infer<typeof SeedMissionReducer>;
export type SetModeParams = __Infer<typeof SetModeReducer>;

