// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  missionId: __t.string().primaryKey().name("mission_id"),
  selectedInterventionId: __t.option(__t.string()).name("selected_intervention_id"),
  status: __t.string(),
  scenarioScore: __t.f64().name("scenario_score"),
  updatedAt: __t.timestamp().name("updated_at"),
  updatedBy: __t.option(__t.identity()).name("updated_by"),
});
