// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  slug: __t.string(),
  title: __t.string(),
  category: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  summary: __t.string(),
  whyHere: __t.string().name("why_here"),
  dataSourceId: __t.option(__t.string()).name("data_source_id"),
  baselineMetricsJson: __t.string().name("baseline_metrics_json"),
  isDeep: __t.bool().name("is_deep"),
});
