// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  displayName: __t.option(__t.string()).name("display_name"),
  joinedAt: __t.timestamp().name("joined_at"),
  selectedMissionId: __t.option(__t.string()).name("selected_mission_id"),
  currentMode: __t.string().name("current_mode"),
});
