// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  slug: __t.string(),
  title: __t.string(),
  category: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  summary: __t.string(),
  whyHere: __t.string(),
  dataSourceId: __t.option(__t.string()),
  baselineMetricsJson: __t.string(),
  isDeep: __t.bool(),
};
