// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CityMemory = __t.object("CityMemory", {
  id: __t.string(),
  title: __t.string(),
  category: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  eventDate: __t.string(),
  summary: __t.string(),
  sourceUrl: __t.string(),
  sceneJson: __t.string(),
});
export type CityMemory = __Infer<typeof CityMemory>;

export const DataSource = __t.object("DataSource", {
  id: __t.string(),
  name: __t.string(),
  publisher: __t.string(),
  url: __t.string(),
  retrievedAt: __t.string(),
  observed: __t.string(),
  derived: __t.string(),
  simulated: __t.string(),
});
export type DataSource = __Infer<typeof DataSource>;

export const Intervention = __t.object("Intervention", {
  id: __t.string(),
  missionId: __t.string(),
  key: __t.string(),
  title: __t.string(),
  description: __t.string(),
  parametersJson: __t.string(),
});
export type Intervention = __Infer<typeof Intervention>;

export const Mission = __t.object("Mission", {
  id: __t.string(),
  slug: __t.string(),
  title: __t.string(),
  category: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  summary: __t.string(),
  whyHere: __t.string(),
  dataSourceId: __t.option(__t.string()),
  baselineMetricsJson: __t.string(),
  isDeep: __t.bool(),
});
export type Mission = __Infer<typeof Mission>;

export const MissionState = __t.object("MissionState", {
  missionId: __t.string(),
  selectedInterventionId: __t.option(__t.string()),
  status: __t.string(),
  scenarioScore: __t.f64(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.option(__t.identity()),
});
export type MissionState = __Infer<typeof MissionState>;

export const PlayerSession = __t.object("PlayerSession", {
  identity: __t.identity(),
  displayName: __t.option(__t.string()),
  joinedAt: __t.timestamp(),
  selectedMissionId: __t.option(__t.string()),
  currentMode: __t.string(),
});
export type PlayerSession = __Infer<typeof PlayerSession>;

export const SimulationRun = __t.object("SimulationRun", {
  id: __t.u64(),
  missionId: __t.string(),
  interventionId: __t.string(),
  baselineJson: __t.string(),
  resultJson: __t.string(),
  assumptionsJson: __t.string(),
  createdAt: __t.timestamp(),
  createdBy: __t.identity(),
});
export type SimulationRun = __Infer<typeof SimulationRun>;

